In [91]:
import pandas as pd
import nltk
import csv
import sys
from nltk import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk import pos_tag
from nltk.stem import SnowballStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter
import math

In [58]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\samya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\samya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\samya\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\samya\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\samya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [59]:
csv.field_size_limit(sys.maxsize)

9223372036854775807

In [60]:
df = pd.read_csv('C:/Users/samya/Downloads/Pandas Data/Practicals DSBDA/train.csv')
df

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [61]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20800 non-null  int64
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64
dtypes: int64(2), object(3)
memory usage: 812.6+ KB

In [63]:
df.describe()

                 id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [64]:
df['text'] = df['text'].fillna("")

In [65]:
text = df['text'][0]
text

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide, it looks like we also know who the second-worst person is as well. It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey. They found out via a tweet from one of the Republican committee chairmen. \nAs we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewing emails it had recently discovered in order to see if they contained classified information. Not long after this letter went out, Oversight Committee Chairman Jason Chaffetz set the political world ablaze with this tweet. FBI Dir just informed me, "The FBI has learned of the existence of emails that appear to be pertinent to the investigation." Case reopened \n— Jason Chaffetz (@jasoninthehouse) October 28, 2016 \nOf course, we now know that this was not the case . Comey was actually saying that it was reviewing the emails in light of “an unrelated case”–which we now know to be Anthony Weiner’s sexting with a teenager. But apparently such little things as facts didn’t matter to Chaffetz. The Utah Republican had already vowed to initiate a raft of investigations if Hillary wins–at least two years’ worth, and possibly an entire term’s worth of them. Apparently Chaffetz thought the FBI was already doing his work for him–resulting in a tweet that briefly roiled the nation before cooler heads realized it was a dud. \nBut according to a senior House Democratic aide, misreading that letter may have been the least of Chaffetz’ sins. That aide told Shareblue that his boss and other Democrats didn’t even know about Comey’s letter at the time–and only found out when they checked Twitter. “Democratic Ranking Members on the relevant committees didn’t receive Comey’s letter until after the Republican Chairmen. In fact, the Democratic Ranking Members didn’ receive it until after the Chairman of the Oversight and Government Reform Committee, Jason Chaffetz, tweeted it out and made it public.” \nSo let’s see if we’ve got this right. The FBI director tells Chaffetz and other GOP committee chairmen about a major development in a potentially politically explosive investigation, and neither Chaffetz nor his other colleagues had the courtesy to let their Democratic counterparts know about it. Instead, according to this aide, he made them find out about it on Twitter. \nThere has already been talk on Daily Kos that Comey himself provided advance notice of this letter to Chaffetz and other Republicans, giving them time to turn on the spin machine. That may make for good theater, but there is nothing so far that even suggests this is the case. After all, there is nothing so far that suggests that Comey was anything other than grossly incompetent and tone-deaf. \nWhat it does suggest, however, is that Chaffetz is acting in a way that makes Dan Burton and Darrell Issa look like models of responsibility and bipartisanship. He didn’t even have the decency to notify ranking member Elijah Cummings about something this explosive. If that doesn’t trample on basic standards of fairness, I don’t know what does. \nGranted, it’s not likely that Chaffetz will have to answer for this. He sits in a ridiculously Republican district anchored in Provo and Orem; it has a Cook Partisan Voting Index of R+25, and gave Mitt Romney a punishing 78 percent of the vote in 2012. Moreover, the Republican House leadership has given its full support to Chaffetz’ planned fishing expedition. But that doesn’t mean we can’t turn the hot lights on him. After all, he is a textbook example of what the House has become under Republican control. And he is also the Second Worst Person in the World. About Darrell Lucus \nDarrell is a 30-something graduate of the University of North Carolina who considers himself a journalist of the old school. An attempt to turn him into a member of the religious right in college only succeeded in turning him into the religious right\'s worst nightmare--a charismatic Christian who is an unapologetic liberal. His desire to stand up for those who have been scared into silence only increased when he survived an abusive three-year marriage. You may know him on Daily Kos as Christian Dem in NC . Follow him on Twitter @DarrellLucus or connect with him on Facebook . Click here to buy Darrell a Mello Yello. Connect'

In [66]:
text = str(text)
print(text[:200])

House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Mic

In [67]:
sentence = sent_tokenize(text)
sentence

['House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey.',
 'But according to a House Democratic aide, it looks like we also know who the second-worst person is as well.',
 'It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey.',
 'They found out via a tweet from one of the Republican committee chairmen.',
 'As we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewing emails it had recently discovered in order to see if they contained classified information.',
 'Not long after this letter went out, Oversight Committee Chairman Jason Chaffetz set the political world ablaze with this tweet.',
 'FBI Dir just informed me, "The FBI has learned of the existence of emails that appear to be pertinent to the investigation."',
 'Case reopened \n— Jason Chaffetz (@jasoninthehouse) October 28, 2016 \nOf course, we now know that this was not the case .',
 'Comey was actually saying that it was reviewing the emails in light of “an unrelated case”–which we now know to be Anthony Weiner’s sexting with a teenager.',
 'But apparently such little things as facts didn’t matter to Chaffetz.',
 'The Utah Republican had already vowed to initiate a raft of investigations if Hillary wins–at least two years’ worth, and possibly an entire term’s worth of them.',
 'Apparently Chaffetz thought the FBI was already doing his work for him–resulting in a tweet that briefly roiled the nation before cooler heads realized it was a dud.',
 'But according to a senior House Democratic aide, misreading that letter may have been the least of Chaffetz’ sins.',
 'That aide told Shareblue that his boss and other Democrats didn’t even know about Comey’s letter at the time–and only found out when they checked Twitter.',
 '“Democratic Ranking Members on the relevant committees didn’t receive Comey’s letter until after the Republican Chairmen.',
 'In fact, the Democratic Ranking Members didn’ receive it until after the Chairman of the Oversight and Government Reform Committee, Jason Chaffetz, tweeted it out and made it public.” \nSo let’s see if we’ve got this right.',
 'The FBI director tells Chaffetz and other GOP committee chairmen about a major development in a potentially politically explosive investigation, and neither Chaffetz nor his other colleagues had the courtesy to let their Democratic counterparts know about it.',
 'Instead, according to this aide, he made them find out about it on Twitter.',
 'There has already been talk on Daily Kos that Comey himself provided advance notice of this letter to Chaffetz and other Republicans, giving them time to turn on the spin machine.',
 'That may make for good theater, but there is nothing so far that even suggests this is the case.',
 'After all, there is nothing so far that suggests that Comey was anything other than grossly incompetent and tone-deaf.',
 'What it does suggest, however, is that Chaffetz is acting in a way that makes Dan Burton and Darrell Issa look like models of responsibility and bipartisanship.',
 'He didn’t even have the decency to notify ranking member Elijah Cummings about something this explosive.',
 'If that doesn’t trample on basic standards of fairness, I don’t know what does.',
 'Granted, it’s not likely that Chaffetz will have to answer for this.',
 'He sits in a ridiculously Republican district anchored in Provo and Orem; it has a Cook Partisan Voting Index of R+25, and gave Mitt Romney a punishing 78 percent of the vote in 2012.',
 'Moreover, the Republican House leadership has given its full support to Chaffetz’ planned fishing expedition.',
 'But that doesn’t mean we can’t turn the hot lights on him.',
 'After all, he is a textbook example of what the House has become under Republican control.',
 'And he is also the Second Worst Person in the World.',
 'About Darrell Lucus \nDarrell is a 30-something graduate of the University of North Carolina who considers himself a journalist of the old school.',
 "An attempt to turn him into a member of the religious right in college only succeeded in turning him into the religious right's worst nightmare--a charismatic Christian who is an unapologetic liberal.",
 'His desire to stand up for those who have been scared into silence only increased when he survived an abusive three-year marriage.',
 'You may know him on Daily Kos as Christian Dem in NC .',
 'Follow him on Twitter @DarrellLucus or connect with him on Facebook .',
 'Click here to buy Darrell a Mello Yello.',
 'Connect']

In [68]:
sentence = sent_tokenize(text)
sentence

['House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey.',
 'But according to a House Democratic aide, it looks like we also know who the second-worst person is as well.',
 'It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey.',
 'They found out via a tweet from one of the Republican committee chairmen.',
 'As we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewing emails it had recently discovered in order to see if they contained classified information.',
 'Not long after this letter went out, Oversight Committee Chairman Jason Chaffetz set the political world ablaze with this tweet.',
 'FBI Dir just informed me, "The FBI has learned of the existence of emails that appear to be pertinent to the investigation."',
 'Case reopened \n— Jason Chaffetz (@jasoninthehouse) October 28, 2016 \nOf course, we now know that this was not the case .',
 'Comey was actually saying that it was reviewing the emails in light of “an unrelated case”–which we now know to be Anthony Weiner’s sexting with a teenager.',
 'But apparently such little things as facts didn’t matter to Chaffetz.',
 'The Utah Republican had already vowed to initiate a raft of investigations if Hillary wins–at least two years’ worth, and possibly an entire term’s worth of them.',
 'Apparently Chaffetz thought the FBI was already doing his work for him–resulting in a tweet that briefly roiled the nation before cooler heads realized it was a dud.',
 'But according to a senior House Democratic aide, misreading that letter may have been the least of Chaffetz’ sins.',
 'That aide told Shareblue that his boss and other Democrats didn’t even know about Comey’s letter at the time–and only found out when they checked Twitter.',
 '“Democratic Ranking Members on the relevant committees didn’t receive Comey’s letter until after the Republican Chairmen.',
 'In fact, the Democratic Ranking Members didn’ receive it until after the Chairman of the Oversight and Government Reform Committee, Jason Chaffetz, tweeted it out and made it public.” \nSo let’s see if we’ve got this right.',
 'The FBI director tells Chaffetz and other GOP committee chairmen about a major development in a potentially politically explosive investigation, and neither Chaffetz nor his other colleagues had the courtesy to let their Democratic counterparts know about it.',
 'Instead, according to this aide, he made them find out about it on Twitter.',
 'There has already been talk on Daily Kos that Comey himself provided advance notice of this letter to Chaffetz and other Republicans, giving them time to turn on the spin machine.',
 'That may make for good theater, but there is nothing so far that even suggests this is the case.',
 'After all, there is nothing so far that suggests that Comey was anything other than grossly incompetent and tone-deaf.',
 'What it does suggest, however, is that Chaffetz is acting in a way that makes Dan Burton and Darrell Issa look like models of responsibility and bipartisanship.',
 'He didn’t even have the decency to notify ranking member Elijah Cummings about something this explosive.',
 'If that doesn’t trample on basic standards of fairness, I don’t know what does.',
 'Granted, it’s not likely that Chaffetz will have to answer for this.',
 'He sits in a ridiculously Republican district anchored in Provo and Orem; it has a Cook Partisan Voting Index of R+25, and gave Mitt Romney a punishing 78 percent of the vote in 2012.',
 'Moreover, the Republican House leadership has given its full support to Chaffetz’ planned fishing expedition.',
 'But that doesn’t mean we can’t turn the hot lights on him.',
 'After all, he is a textbook example of what the House has become under Republican control.',
 'And he is also the Second Worst Person in the World.',
 'About Darrell Lucus \nDarrell is a 30-something graduate of the University of North Carolina who considers himself a journalist of the old school.',
 "An attempt to turn him into a member of the religious right in college only succeeded in turning him into the religious right's worst nightmare--a charismatic Christian who is an unapologetic liberal.",
 'His desire to stand up for those who have been scared into silence only increased when he survived an abusive three-year marriage.',
 'You may know him on Daily Kos as Christian Dem in NC .',
 'Follow him on Twitter @DarrellLucus or connect with him on Facebook .',
 'Click here to buy Darrell a Mello Yello.',
 'Connect']

In [69]:
word = word_tokenize(text)
word

['House',
 'Dem',
 'Aide',
 ':',
 'We',
 'Didn',
 '’',
 't',
 'Even',
 'See',
 'Comey',
 '’',
 's',
 'Letter',
 'Until',
 'Jason',
 'Chaffetz',
 'Tweeted',
 'It',
 'By',
 'Darrell',
 'Lucus',
 'on',
 'October',
 '30',
 ',',
 '2016',
 'Subscribe',
 'Jason',
 'Chaffetz',
 'on',
 'the',
 'stump',
 'in',
 'American',
 'Fork',
 ',',
 'Utah',
 '(',
 'image',
 'courtesy',
 'Michael',
 'Jolley',
 ',',
 'available',
 'under',
 'a',
 'Creative',
 'Commons-BY',
 'license',
 ')',
 'With',
 'apologies',
 'to',
 'Keith',
 'Olbermann',
 ',',
 'there',
 'is',
 'no',
 'doubt',
 'who',
 'the',
 'Worst',
 'Person',
 'in',
 'The',
 'World',
 'is',
 'this',
 'week–FBI',
 'Director',
 'James',
 'Comey',
 '.',
 'But',
 'according',
 'to',
 'a',
 'House',
 'Democratic',
 'aide',
 ',',
 'it',
 'looks',
 'like',
 'we',
 'also',
 'know',
 'who',
 'the',
 'second-worst',
 'person',
 'is',
 'as',
 'well',
 '.',
 'It',
 'turns',
 'out',
 'that',
 'when',
 'Comey',
 'sent',
 'his',
 'now-infamous',
 'letter',
 'announcing',
 'that',
 'the',
 'FBI',
 'was',
 'looking',
 'into',
 'emails',
 'that',
 'may',
 'be',
 'related',
 'to',
 'Hillary',
 'Clinton',
 '’',
 's',
 'email',
 'server',
 ',',
 'the',
 'ranking',
 'Democrats',
 'on',
 'the',
 'relevant',
 'committees',
 'didn',
 '’',
 't',
 'hear',
 'about',
 'it',
 'from',
 'Comey',
 '.',
 'They',
 'found',
 'out',
 'via',
 'a',
 'tweet',
 'from',
 'one',
 'of',
 'the',
 'Republican',
 'committee',
 'chairmen',
 '.',
 'As',
 'we',
 'now',
 'know',
 ',',
 'Comey',
 'notified',
 'the',
 'Republican',
 'chairmen',
 'and',
 'Democratic',
 'ranking',
 'members',
 'of',
 'the',
 'House',
 'Intelligence',
 ',',
 'Judiciary',
 ',',
 'and',
 'Oversight',
 'committees',
 'that',
 'his',
 'agency',
 'was',
 'reviewing',
 'emails',
 'it',
 'had',
 'recently',
 'discovered',
 'in',
 'order',
 'to',
 'see',
 'if',
 'they',
 'contained',
 'classified',
 'information',
 '.',
 'Not',
 'long',
 'after',
 'this',
 'letter',
 'went',
 'out',
 ',',
 'Oversight',
 'Committee',
 'Chairman',
 'Jason',
 'Chaffetz',
 'set',
 'the',
 'political',
 'world',
 'ablaze',
 'with',
 'this',
 'tweet',
 '.',
 'FBI',
 'Dir',
 'just',
 'informed',
 'me',
 ',',
 '``',
 'The',
 'FBI',
 'has',
 'learned',
 'of',
 'the',
 'existence',
 'of',
 'emails',
 'that',
 'appear',
 'to',
 'be',
 'pertinent',
 'to',
 'the',
 'investigation',
 '.',
 "''",
 'Case',
 'reopened',
 '—',
 'Jason',
 'Chaffetz',
 '(',
 '@',
 'jasoninthehouse',
 ')',
 'October',
 '28',
 ',',
 '2016',
 'Of',
 'course',
 ',',
 'we',
 'now',
 'know',
 'that',
 'this',
 'was',
 'not',
 'the',
 'case',
 '.',
 'Comey',
 'was',
 'actually',
 'saying',
 'that',
 'it',
 'was',
 'reviewing',
 'the',
 'emails',
 'in',
 'light',
 'of',
 '“',
 'an',
 'unrelated',
 'case',
 '”',
 '–which',
 'we',
 'now',
 'know',
 'to',
 'be',
 'Anthony',
 'Weiner',
 '’',
 's',
 'sexting',
 'with',
 'a',
 'teenager',
 '.',
 'But',
 'apparently',
 'such',
 'little',
 'things',
 'as',
 'facts',
 'didn',
 '’',
 't',
 'matter',
 'to',
 'Chaffetz',
 '.',
 'The',
 'Utah',
 'Republican',
 'had',
 'already',
 'vowed',
 'to',
 'initiate',
 'a',
 'raft',
 'of',
 'investigations',
 'if',
 'Hillary',
 'wins–at',
 'least',
 'two',
 'years',
 '’',
 'worth',
 ',',
 'and',
 'possibly',
 'an',
 'entire',
 'term',
 '’',
 's',
 'worth',
 'of',
 'them',
 '.',
 'Apparently',
 'Chaffetz',
 'thought',
 'the',
 'FBI',
 'was',
 'already',
 'doing',
 'his',
 'work',
 'for',
 'him–resulting',
 'in',
 'a',
 'tweet',
 'that',
 'briefly',
 'roiled',
 'the',
 'nation',
 'before',
 'cooler',
 'heads',
 'realized',
 'it',
 'was',
 'a',
 'dud',
 '.',
 'But',
 'according',
 'to',
 'a',
 'senior',
 'House',
 'Democratic',
 'aide',
 ',',
 'misreading',
 'that',
 'letter',
 'may',
 'have',
 'been',
 'the',
 'least',
 'of',
 'Chaffetz',
 '’',
 'sins',
 '.',
 'That',
 'aide',
 'told',
 'Shareblue',
 'that',
 'his',
 'boss',
 'and',
 'other',
 'Democrats',
 'didn',
 '’',
 't',
 'even',
 'know',
 'about',
 'Comey',
 '’',
 's',
 'letter',
 'at',
 'the',
 'time–and',
 'only',
 'found',
 'out',
 'when',
 'they',
 'checked',
 'Twitter',
 '.',
 '“',
 'Democratic',
 'Ranking',
 'Members',
 'on',
 'the',
 'relevant',
 'committees',
 'didn',
 '’',
 't',
 'receive',
 'Comey',
 '’',
 's',
 'letter',
 'until',
 'after',
 'the',
 'Republican',
 'Chairmen',
 '.',
 'In',
 'fact',
 ',',
 'the',
 'Democratic',
 'Ranking',
 'Members',
 'didn',
 '’',
 'receive',
 'it',
 'until',
 'after',
 'the',
 'Chairman',
 'of',
 'the',
 'Oversight',
 'and',
 'Government',
 'Reform',
 'Committee',
 ',',
 'Jason',
 'Chaffetz',
 ',',
 'tweeted',
 'it',
 'out',
 'and',
 'made',
 'it',
 'public.',
 '”',
 'So',
 'let',
 '’',
 's',
 'see',
 'if',
 'we',
 '’',
 've',
 'got',
 'this',
 'right',
 '.',
 'The',
 'FBI',
 'director',
 'tells',
 'Chaffetz',
 'and',
 'other',
 'GOP',
 'committee',
 'chairmen',
 'about',
 'a',
 'major',
 'development',
 'in',
 'a',
 'potentially',
 'politically',
 'explosive',
 'investigation',
 ',',
 'and',
 'neither',
 'Chaffetz',
 'nor',
 'his',
 'other',
 'colleagues',
 'had',
 'the',
 'courtesy',
 'to',
 'let',
 'their',
 'Democratic',
 'counterparts',
 'know',
 'about',
 'it',
 '.',
 'Instead',
 ',',
 'according',
 'to',
 'this',
 'aide',
 ',',
 'he',
 'made',
 'them',
 'find',
 'out',
 'about',
 'it',
 'on',
 'Twitter',
 '.',
 'There',
 'has',
 'already',
 'been',
 'talk',
 'on',
 'Daily',
 'Kos',
 'that',
 'Comey',
 'himself',
 'provided',
 'advance',
 'notice',
 'of',
 'this',
 'letter',
 'to',
 'Chaffetz',
 'and',
 'other',
 'Republicans',
 ',',
 'giving',
 'them',
 'time',
 'to',
 'turn',
 'on',
 'the',
 'spin',
 'machine',
 '.',
 'That',
 'may',
 'make',
 'for',
 'good',
 'theater',
 ',',
 'but',
 'there',
 'is',
 'nothing',
 'so',
 'far',
 'that',
 'even',
 'suggests',
 'this',
 'is',
 'the',
 'case',
 '.',
 'After',
 'all',
 ',',
 'there',
 'is',
 'nothing',
 'so',
 'far',
 'that',
 'suggests',
 'that',
 'Comey',
 'was',
 'anything',
 'other',
 'than',
 'grossly',
 'incompetent',
 'and',
 'tone-deaf',
 '.',
 'What',
 'it',
 'does',
 'suggest',
 ',',
 'however',
 ',',
 'is',
 'that',
 'Chaffetz',
 'is',
 'acting',
 'in',
 'a',
 'way',
 'that',
 'makes',
 'Dan',
 'Burton',
 'and',
 'Darrell',
 'Issa',
 'look',
 'like',
 'models',
 'of',
 'responsibility',
 'and',
 'bipartisanship',
 '.',
 'He',
 'didn',
 '’',
 't',
 'even',
 'have',
 'the',
 'decency',
 'to',
 'notify',
 'ranking',
 'member',
 'Elijah',
 'Cummings',
 'about',
 'something',
 'this',
 'explosive',
 '.',
 'If',
 'that',
 'doesn',
 '’',
 't',
 'trample',
 'on',
 'basic',
 'standards',
 'of',
 'fairness',
 ',',
 'I',
 'don',
 '’',
 't',
 'know',
 'what',
 'does',
 '.',
 'Granted',
 ',',
 'it',
 '’',
 's',
 'not',
 'likely',
 'that',
 'Chaffetz',
 'will',
 'have',
 'to',
 'answer',
 'for',
 'this',
 '.',
 'He',
 'sits',
 'in',
 'a',
 'ridiculously',
 'Republican',
 'district',
 'anchored',
 'in',
 'Provo',
 'and',
 'Orem',
 ';',
 'it',
 'has',
 'a',
 'Cook',
 'Partisan',
 'Voting',
 'Index',
 'of',
 'R+25',
 ',',
 'and',
 'gave',
 'Mitt',
 'Romney',
 'a',
 'punishing',
 '78',
 'percent',
 'of',
 'the',
 'vote',
 'in',
 '2012',
 '.',
 'Moreover',
 ',',
 'the',
 'Republican',
 'House',
 'leadership',
 'has',
 'given',
 'its',
 'full',
 'support',
 'to',
 'Chaffetz',
 '’',
 'planned',
 'fishing',
 'expedition',
 '.',
 'But',
 'that',
 'doesn',
 '’',
 't',
 'mean',
 'we',
 'can',
 '’',
 't',
 'turn',
 'the',
 'hot',
 'lights',
 'on',
 'him',
 '.',
 'After',
 'all',
 ',',
 'he',
 'is',
 'a',
 'textbook',
 'example',
 'of',
 'what',
 'the',
 'House',
 'has',
 'become',
 'under',
 'Republican',
 'control',
 '.',
 'And',
 'he',
 'is',
 'also',
 'the',
 'Second',
 'Worst',
 'Person',
 'in',
 'the',
 'World',
 '.',
 'About',
 'Darrell',
 'Lucus',
 'Darrell',
 'is',
 'a',
 '30-something',
 'graduate',
 'of',
 'the',
 'University',
 'of',
 'North',
 'Carolina',
 'who',
 'considers',
 'himself',
 'a',
 'journalist',
 'of',
 'the',
 'old',
 'school',
 '.',
 'An',
 'attempt',
 'to',
 'turn',
 'him',
 'into',
 'a',
 'member',
 'of',
 'the',
 'religious',
 'right',
 'in',
 'college',
 'only',
 'succeeded',
 'in',
 'turning',
 'him',
 'into',
 'the',
 'religious',
 'right',
 "'s",
 'worst',
 'nightmare',
 '--',
 'a',
 'charismatic',
 'Christian',
 'who',
 'is',
 'an',
 'unapologetic',
 'liberal',
 '.',
 'His',
 'desire',
 'to',
 'stand',
 'up',
 'for',
 'those',
 'who',
 'have',
 'been',
 'scared',
 'into',
 'silence',
 'only',
 'increased',
 'when',
 'he',
 'survived',
 'an',
 'abusive',
 'three-year',
 'marriage',
 '.',
 'You',
 'may',
 'know',
 'him',
 'on',
 'Daily',
 'Kos',
 'as',
 'Christian',
 'Dem',
 'in',
 'NC',
 '.',
 'Follow',
 'him',
 'on',
 'Twitter',
 '@',
 'DarrellLucus',
 'or',
 'connect',
 'with',
 'him',
 'on',
 'Facebook',
 '.',
 'Click',
 'here',
 'to',
 'buy',
 'Darrell',
 'a',
 'Mello',
 'Yello',
 '.',
 'Connect']

In [70]:
stop_words = stopwords.words('english')
stop_words

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [71]:
filter = []
for w in word:
    if w.lower() not in stop_words:
        filter.append(w)

filter

['House',
 'Dem',
 'Aide',
 ':',
 '’',
 'Even',
 'See',
 'Comey',
 '’',
 'Letter',
 'Jason',
 'Chaffetz',
 'Tweeted',
 'Darrell',
 'Lucus',
 'October',
 '30',
 ',',
 '2016',
 'Subscribe',
 'Jason',
 'Chaffetz',
 'stump',
 'American',
 'Fork',
 ',',
 'Utah',
 '(',
 'image',
 'courtesy',
 'Michael',
 'Jolley',
 ',',
 'available',
 'Creative',
 'Commons-BY',
 'license',
 ')',
 'apologies',
 'Keith',
 'Olbermann',
 ',',
 'doubt',
 'Worst',
 'Person',
 'World',
 'week–FBI',
 'Director',
 'James',
 'Comey',
 '.',
 'according',
 'House',
 'Democratic',
 'aide',
 ',',
 'looks',
 'like',
 'also',
 'know',
 'second-worst',
 'person',
 'well',
 '.',
 'turns',
 'Comey',
 'sent',
 'now-infamous',
 'letter',
 'announcing',
 'FBI',
 'looking',
 'emails',
 'may',
 'related',
 'Hillary',
 'Clinton',
 '’',
 'email',
 'server',
 ',',
 'ranking',
 'Democrats',
 'relevant',
 'committees',
 '’',
 'hear',
 'Comey',
 '.',
 'found',
 'via',
 'tweet',
 'one',
 'Republican',
 'committee',
 'chairmen',
 '.',
 'know',
 ',',
 'Comey',
 'notified',
 'Republican',
 'chairmen',
 'Democratic',
 'ranking',
 'members',
 'House',
 'Intelligence',
 ',',
 'Judiciary',
 ',',
 'Oversight',
 'committees',
 'agency',
 'reviewing',
 'emails',
 'recently',
 'discovered',
 'order',
 'see',
 'contained',
 'classified',
 'information',
 '.',
 'long',
 'letter',
 'went',
 ',',
 'Oversight',
 'Committee',
 'Chairman',
 'Jason',
 'Chaffetz',
 'set',
 'political',
 'world',
 'ablaze',
 'tweet',
 '.',
 'FBI',
 'Dir',
 'informed',
 ',',
 '``',
 'FBI',
 'learned',
 'existence',
 'emails',
 'appear',
 'pertinent',
 'investigation',
 '.',
 "''",
 'Case',
 'reopened',
 '—',
 'Jason',
 'Chaffetz',
 '(',
 '@',
 'jasoninthehouse',
 ')',
 'October',
 '28',
 ',',
 '2016',
 'course',
 ',',
 'know',
 'case',
 '.',
 'Comey',
 'actually',
 'saying',
 'reviewing',
 'emails',
 'light',
 '“',
 'unrelated',
 'case',
 '”',
 '–which',
 'know',
 'Anthony',
 'Weiner',
 '’',
 'sexting',
 'teenager',
 '.',
 'apparently',
 'little',
 'things',
 'facts',
 '’',
 'matter',
 'Chaffetz',
 '.',
 'Utah',
 'Republican',
 'already',
 'vowed',
 'initiate',
 'raft',
 'investigations',
 'Hillary',
 'wins–at',
 'least',
 'two',
 'years',
 '’',
 'worth',
 ',',
 'possibly',
 'entire',
 'term',
 '’',
 'worth',
 '.',
 'Apparently',
 'Chaffetz',
 'thought',
 'FBI',
 'already',
 'work',
 'him–resulting',
 'tweet',
 'briefly',
 'roiled',
 'nation',
 'cooler',
 'heads',
 'realized',
 'dud',
 '.',
 'according',
 'senior',
 'House',
 'Democratic',
 'aide',
 ',',
 'misreading',
 'letter',
 'may',
 'least',
 'Chaffetz',
 '’',
 'sins',
 '.',
 'aide',
 'told',
 'Shareblue',
 'boss',
 'Democrats',
 '’',
 'even',
 'know',
 'Comey',
 '’',
 'letter',
 'time–and',
 'found',
 'checked',
 'Twitter',
 '.',
 '“',
 'Democratic',
 'Ranking',
 'Members',
 'relevant',
 'committees',
 '’',
 'receive',
 'Comey',
 '’',
 'letter',
 'Republican',
 'Chairmen',
 '.',
 'fact',
 ',',
 'Democratic',
 'Ranking',
 'Members',
 '’',
 'receive',
 'Chairman',
 'Oversight',
 'Government',
 'Reform',
 'Committee',
 ',',
 'Jason',
 'Chaffetz',
 ',',
 'tweeted',
 'made',
 'public.',
 '”',
 'let',
 '’',
 'see',
 '’',
 'got',
 'right',
 '.',
 'FBI',
 'director',
 'tells',
 'Chaffetz',
 'GOP',
 'committee',
 'chairmen',
 'major',
 'development',
 'potentially',
 'politically',
 'explosive',
 'investigation',
 ',',
 'neither',
 'Chaffetz',
 'colleagues',
 'courtesy',
 'let',
 'Democratic',
 'counterparts',
 'know',
 '.',
 'Instead',
 ',',
 'according',
 'aide',
 ',',
 'made',
 'find',
 'Twitter',
 '.',
 'already',
 'talk',
 'Daily',
 'Kos',
 'Comey',
 'provided',
 'advance',
 'notice',
 'letter',
 'Chaffetz',
 'Republicans',
 ',',
 'giving',
 'time',
 'turn',
 'spin',
 'machine',
 '.',
 'may',
 'make',
 'good',
 'theater',
 ',',
 'nothing',
 'far',
 'even',
 'suggests',
 'case',
 '.',
 ',',
 'nothing',
 'far',
 'suggests',
 'Comey',
 'anything',
 'grossly',
 'incompetent',
 'tone-deaf',
 '.',
 'suggest',
 ',',
 'however',
 ',',
 'Chaffetz',
 'acting',
 'way',
 'makes',
 'Dan',
 'Burton',
 'Darrell',
 'Issa',
 'look',
 'like',
 'models',
 'responsibility',
 'bipartisanship',
 '.',
 '’',
 'even',
 'decency',
 'notify',
 'ranking',
 'member',
 'Elijah',
 'Cummings',
 'something',
 'explosive',
 '.',
 '’',
 'trample',
 'basic',
 'standards',
 'fairness',
 ',',
 '’',
 'know',
 '.',
 'Granted',
 ',',
 '’',
 'likely',
 'Chaffetz',
 'answer',
 '.',
 'sits',
 'ridiculously',
 'Republican',
 'district',
 'anchored',
 'Provo',
 'Orem',
 ';',
 'Cook',
 'Partisan',
 'Voting',
 'Index',
 'R+25',
 ',',
 'gave',
 'Mitt',
 'Romney',
 'punishing',
 '78',
 'percent',
 'vote',
 '2012',
 '.',
 'Moreover',
 ',',
 'Republican',
 'House',
 'leadership',
 'given',
 'full',
 'support',
 'Chaffetz',
 '’',
 'planned',
 'fishing',
 'expedition',
 '.',
 '’',
 'mean',
 '’',
 'turn',
 'hot',
 'lights',
 '.',
 ',',
 'textbook',
 'example',
 'House',
 'become',
 'Republican',
 'control',
 '.',
 'also',
 'Second',
 'Worst',
 'Person',
 'World',
 '.',
 'Darrell',
 'Lucus',
 'Darrell',
 '30-something',
 'graduate',
 'University',
 'North',
 'Carolina',
 'considers',
 'journalist',
 'old',
 'school',
 '.',
 'attempt',
 'turn',
 'member',
 'religious',
 'right',
 'college',
 'succeeded',
 'turning',
 'religious',
 'right',
 "'s",
 'worst',
 'nightmare',
 '--',
 'charismatic',
 'Christian',
 'unapologetic',
 'liberal',
 '.',
 'desire',
 'stand',
 'scared',
 'silence',
 'increased',
 'survived',
 'abusive',
 'three-year',
 'marriage',
 '.',
 'may',
 'know',
 'Daily',
 'Kos',
 'Christian',
 'Dem',
 'NC',
 '.',
 'Follow',
 'Twitter',
 '@',
 'DarrellLucus',
 'connect',
 'Facebook',
 '.',
 'Click',
 'buy',
 'Darrell',
 'Mello',
 'Yello',
 '.',
 'Connect']

In [72]:
clean = [c for c in filter if c.isalnum()]
clean

['House',
 'Dem',
 'Aide',
 'Even',
 'See',
 'Comey',
 'Letter',
 'Jason',
 'Chaffetz',
 'Tweeted',
 'Darrell',
 'Lucus',
 'October',
 '30',
 '2016',
 'Subscribe',
 'Jason',
 'Chaffetz',
 'stump',
 'American',
 'Fork',
 'Utah',
 'image',
 'courtesy',
 'Michael',
 'Jolley',
 'available',
 'Creative',
 'license',
 'apologies',
 'Keith',
 'Olbermann',
 'doubt',
 'Worst',
 'Person',
 'World',
 'Director',
 'James',
 'Comey',
 'according',
 'House',
 'Democratic',
 'aide',
 'looks',
 'like',
 'also',
 'know',
 'person',
 'well',
 'turns',
 'Comey',
 'sent',
 'letter',
 'announcing',
 'FBI',
 'looking',
 'emails',
 'may',
 'related',
 'Hillary',
 'Clinton',
 'email',
 'server',
 'ranking',
 'Democrats',
 'relevant',
 'committees',
 'hear',
 'Comey',
 'found',
 'via',
 'tweet',
 'one',
 'Republican',
 'committee',
 'chairmen',
 'know',
 'Comey',
 'notified',
 'Republican',
 'chairmen',
 'Democratic',
 'ranking',
 'members',
 'House',
 'Intelligence',
 'Judiciary',
 'Oversight',
 'committees',
 'agency',
 'reviewing',
 'emails',
 'recently',
 'discovered',
 'order',
 'see',
 'contained',
 'classified',
 'information',
 'long',
 'letter',
 'went',
 'Oversight',
 'Committee',
 'Chairman',
 'Jason',
 'Chaffetz',
 'set',
 'political',
 'world',
 'ablaze',
 'tweet',
 'FBI',
 'Dir',
 'informed',
 'FBI',
 'learned',
 'existence',
 'emails',
 'appear',
 'pertinent',
 'investigation',
 'Case',
 'reopened',
 'Jason',
 'Chaffetz',
 'jasoninthehouse',
 'October',
 '28',
 '2016',
 'course',
 'know',
 'case',
 'Comey',
 'actually',
 'saying',
 'reviewing',
 'emails',
 'light',
 'unrelated',
 'case',
 'know',
 'Anthony',
 'Weiner',
 'sexting',
 'teenager',
 'apparently',
 'little',
 'things',
 'facts',
 'matter',
 'Chaffetz',
 'Utah',
 'Republican',
 'already',
 'vowed',
 'initiate',
 'raft',
 'investigations',
 'Hillary',
 'least',
 'two',
 'years',
 'worth',
 'possibly',
 'entire',
 'term',
 'worth',
 'Apparently',
 'Chaffetz',
 'thought',
 'FBI',
 'already',
 'work',
 'tweet',
 'briefly',
 'roiled',
 'nation',
 'cooler',
 'heads',
 'realized',
 'dud',
 'according',
 'senior',
 'House',
 'Democratic',
 'aide',
 'misreading',
 'letter',
 'may',
 'least',
 'Chaffetz',
 'sins',
 'aide',
 'told',
 'Shareblue',
 'boss',
 'Democrats',
 'even',
 'know',
 'Comey',
 'letter',
 'found',
 'checked',
 'Twitter',
 'Democratic',
 'Ranking',
 'Members',
 'relevant',
 'committees',
 'receive',
 'Comey',
 'letter',
 'Republican',
 'Chairmen',
 'fact',
 'Democratic',
 'Ranking',
 'Members',
 'receive',
 'Chairman',
 'Oversight',
 'Government',
 'Reform',
 'Committee',
 'Jason',
 'Chaffetz',
 'tweeted',
 'made',
 'let',
 'see',
 'got',
 'right',
 'FBI',
 'director',
 'tells',
 'Chaffetz',
 'GOP',
 'committee',
 'chairmen',
 'major',
 'development',
 'potentially',
 'politically',
 'explosive',
 'investigation',
 'neither',
 'Chaffetz',
 'colleagues',
 'courtesy',
 'let',
 'Democratic',
 'counterparts',
 'know',
 'Instead',
 'according',
 'aide',
 'made',
 'find',
 'Twitter',
 'already',
 'talk',
 'Daily',
 'Kos',
 'Comey',
 'provided',
 'advance',
 'notice',
 'letter',
 'Chaffetz',
 'Republicans',
 'giving',
 'time',
 'turn',
 'spin',
 'machine',
 'may',
 'make',
 'good',
 'theater',
 'nothing',
 'far',
 'even',
 'suggests',
 'case',
 'nothing',
 'far',
 'suggests',
 'Comey',
 'anything',
 'grossly',
 'incompetent',
 'suggest',
 'however',
 'Chaffetz',
 'acting',
 'way',
 'makes',
 'Dan',
 'Burton',
 'Darrell',
 'Issa',
 'look',
 'like',
 'models',
 'responsibility',
 'bipartisanship',
 'even',
 'decency',
 'notify',
 'ranking',
 'member',
 'Elijah',
 'Cummings',
 'something',
 'explosive',
 'trample',
 'basic',
 'standards',
 'fairness',
 'know',
 'Granted',
 'likely',
 'Chaffetz',
 'answer',
 'sits',
 'ridiculously',
 'Republican',
 'district',
 'anchored',
 'Provo',
 'Orem',
 'Cook',
 'Partisan',
 'Voting',
 'Index',
 'gave',
 'Mitt',
 'Romney',
 'punishing',
 '78',
 'percent',
 'vote',
 '2012',
 'Moreover',
 'Republican',
 'House',
 'leadership',
 'given',
 'full',
 'support',
 'Chaffetz',
 'planned',
 'fishing',
 'expedition',
 'mean',
 'turn',
 'hot',
 'lights',
 'textbook',
 'example',
 'House',
 'become',
 'Republican',
 'control',
 'also',
 'Second',
 'Worst',
 'Person',
 'World',
 'Darrell',
 'Lucus',
 'Darrell',
 'graduate',
 'University',
 'North',
 'Carolina',
 'considers',
 'journalist',
 'old',
 'school',
 'attempt',
 'turn',
 'member',
 'religious',
 'right',
 'college',
 'succeeded',
 'turning',
 'religious',
 'right',
 'worst',
 'nightmare',
 'charismatic',
 'Christian',
 'unapologetic',
 'liberal',
 'desire',
 'stand',
 'scared',
 'silence',
 'increased',
 'survived',
 'abusive',
 'marriage',
 'may',
 'know',
 'Daily',
 'Kos',
 'Christian',
 'Dem',
 'NC',
 'Follow',
 'Twitter',
 'DarrellLucus',
 'connect',
 'Facebook',
 'Click',
 'buy',
 'Darrell',
 'Mello',
 'Yello',
 'Connect']

In [73]:
pos_tags = pos_tag(clean)
pos_tags

[('House', 'NNP'),
 ('Dem', 'NNP'),
 ('Aide', 'NNP'),
 ('Even', 'NNP'),
 ('See', 'NNP'),
 ('Comey', 'NNP'),
 ('Letter', 'NNP'),
 ('Jason', 'NNP'),
 ('Chaffetz', 'NNP'),
 ('Tweeted', 'NNP'),
 ('Darrell', 'NNP'),
 ('Lucus', 'NNP'),
 ('October', 'NNP'),
 ('30', 'CD'),
 ('2016', 'CD'),
 ('Subscribe', 'NNP'),
 ('Jason', 'NNP'),
 ('Chaffetz', 'NNP'),
 ('stump', 'JJ'),
 ('American', 'NNP'),
 ('Fork', 'NNP'),
 ('Utah', 'NNP'),
 ('image', 'NN'),
 ('courtesy', 'NN'),
 ('Michael', 'NNP'),
 ('Jolley', 'NNP'),
 ('available', 'JJ'),
 ('Creative', 'NNP'),
 ('license', 'NN'),
 ('apologies', 'NNS'),
 ('Keith', 'NNP'),
 ('Olbermann', 'NNP'),
 ('doubt', 'NN'),
 ('Worst', 'NNP'),
 ('Person', 'NNP'),
 ('World', 'NNP'),
 ('Director', 'NNP'),
 ('James', 'NNP'),
 ('Comey', 'NNP'),
 ('according', 'VBG'),
 ('House', 'NNP'),
 ('Democratic', 'JJ'),
 ('aide', 'RB'),
 ('looks', 'VBZ'),
 ('like', 'IN'),
 ('also', 'RB'),
 ('know', 'VBP'),
 ('person', 'NN'),
 ('well', 'RB'),
 ('turns', 'VBZ'),
 ('Comey', 'NNP'),
 ('sent', 'VBD'),
 ('letter', 'NN'),
 ('announcing', 'VBG'),
 ('FBI', 'NNP'),
 ('looking', 'VBG'),
 ('emails', 'NNS'),
 ('may', 'MD'),
 ('related', 'VB'),
 ('Hillary', 'NNP'),
 ('Clinton', 'NNP'),
 ('email', 'VBP'),
 ('server', 'NN'),
 ('ranking', 'NN'),
 ('Democrats', 'NNPS'),
 ('relevant', 'VBP'),
 ('committees', 'NNS'),
 ('hear', 'VBP'),
 ('Comey', 'NNP'),
 ('found', 'VBD'),
 ('via', 'IN'),
 ('tweet', 'NN'),
 ('one', 'CD'),
 ('Republican', 'NNP'),
 ('committee', 'NN'),
 ('chairmen', 'NNS'),
 ('know', 'VBP'),
 ('Comey', 'NNP'),
 ('notified', 'VBD'),
 ('Republican', 'NNP'),
 ('chairmen', 'NNS'),
 ('Democratic', 'JJ'),
 ('ranking', 'VBG'),
 ('members', 'NNS'),
 ('House', 'NNP'),
 ('Intelligence', 'NNP'),
 ('Judiciary', 'NNP'),
 ('Oversight', 'NNP'),
 ('committees', 'NNS'),
 ('agency', 'NN'),
 ('reviewing', 'VBG'),
 ('emails', 'NNS'),
 ('recently', 'RB'),
 ('discovered', 'VBD'),
 ('order', 'NN'),
 ('see', 'NN'),
 ('contained', 'VBD'),
 ('classified', 'JJ'),
 ('information', 'NN'),
 ('long', 'RB'),
 ('letter', 'NN'),
 ('went', 'VBD'),
 ('Oversight', 'NNP'),
 ('Committee', 'NNP'),
 ('Chairman', 'NNP'),
 ('Jason', 'NNP'),
 ('Chaffetz', 'NNP'),
 ('set', 'VBD'),
 ('political', 'JJ'),
 ('world', 'NN'),
 ('ablaze', 'NN'),
 ('tweet', 'NN'),
 ('FBI', 'NNP'),
 ('Dir', 'NNP'),
 ('informed', 'VBD'),
 ('FBI', 'NNP'),
 ('learned', 'VBD'),
 ('existence', 'NN'),
 ('emails', 'NNS'),
 ('appear', 'VBP'),
 ('pertinent', 'JJ'),
 ('investigation', 'NN'),
 ('Case', 'NNP'),
 ('reopened', 'VBD'),
 ('Jason', 'NNP'),
 ('Chaffetz', 'NNP'),
 ('jasoninthehouse', 'NN'),
 ('October', 'NNP'),
 ('28', 'CD'),
 ('2016', 'CD'),
 ('course', 'NN'),
 ('know', 'VBP'),
 ('case', 'NN'),
 ('Comey', 'NNP'),
 ('actually', 'RB'),
 ('saying', 'VBG'),
 ('reviewing', 'VBG'),
 ('emails', 'NNS'),
 ('light', 'RB'),
 ('unrelated', 'JJ'),
 ('case', 'NN'),
 ('know', 'VBP'),
 ('Anthony', 'NNP'),
 ('Weiner', 'NNP'),
 ('sexting', 'VBG'),
 ('teenager', 'NN'),
 ('apparently', 'RB'),
 ('little', 'JJ'),
 ('things', 'NNS'),
 ('facts', 'NNS'),
 ('matter', 'RB'),
 ('Chaffetz', 'NNP'),
 ('Utah', 'NNP'),
 ('Republican', 'NNP'),
 ('already', 'RB'),
 ('vowed', 'VBD'),
 ('initiate', 'JJ'),
 ('raft', 'NN'),
 ('investigations', 'NNS'),
 ('Hillary', 'NNP'),
 ('least', 'JJS'),
 ('two', 'CD'),
 ('years', 'NNS'),
 ('worth', 'IN'),
 ('possibly', 'RB'),
 ('entire', 'JJ'),
 ('term', 'NN'),
 ('worth', 'NN'),
 ('Apparently', 'NNP'),
 ('Chaffetz', 'NNP'),
 ('thought', 'VBD'),
 ('FBI', 'NNP'),
 ('already', 'RB'),
 ('work', 'VBP'),
 ('tweet', 'RB'),
 ('briefly', 'JJ'),
 ('roiled', 'VBD'),
 ('nation', 'NN'),
 ('cooler', 'NN'),
 ('heads', 'NNS'),
 ('realized', 'VBD'),
 ('dud', 'NN'),
 ('according', 'VBG'),
 ('senior', 'JJ'),
 ('House', 'NNP'),
 ('Democratic', 'JJ'),
 ('aide', 'IN'),
 ('misreading', 'VBG'),
 ('letter', 'NN'),
 ('may', 'MD'),
 ('least', 'VB'),
 ('Chaffetz', 'NNP'),
 ('sins', 'NNS'),
 ('aide', 'VBP'),
 ('told', 'VBD'),
 ('Shareblue', 'NNP'),
 ('boss', 'IN'),
 ('Democrats', 'NNPS'),
 ('even', 'RB'),
 ('know', 'VBP'),
 ('Comey', 'NNP'),
 ('letter', 'NN'),
 ('found', 'VBD'),
 ('checked', 'VBD'),
 ('Twitter', 'NNP'),
 ('Democratic', 'NNP'),
 ('Ranking', 'NNP'),
 ('Members', 'NNP'),
 ('relevant', 'VBP'),
 ('committees', 'NNS'),
 ('receive', 'VBP'),
 ('Comey', 'NNP'),
 ('letter', 'NN'),
 ('Republican', 'NNP'),
 ('Chairmen', 'NNP'),
 ('fact', 'NN'),
 ('Democratic', 'JJ'),
 ('Ranking', 'NNP'),
 ('Members', 'NNP'),
 ('receive', 'VBP'),
 ('Chairman', 'NNP'),
 ('Oversight', 'NNP'),
 ('Government', 'NNP'),
 ('Reform', 'NNP'),
 ('Committee', 'NNP'),
 ('Jason', 'NNP'),
 ('Chaffetz', 'NNP'),
 ('tweeted', 'VBD'),
 ('made', 'VBN'),
 ('let', 'NN'),
 ('see', 'VB'),
 ('got', 'VBD'),
 ('right', 'JJ'),
 ('FBI', 'NNP'),
 ('director', 'NN'),
 ('tells', 'NNS'),
 ('Chaffetz', 'NNP'),
 ('GOP', 'NNP'),
 ('committee', 'NN'),
 ('chairmen', 'NNS'),
 ('major', 'JJ'),
 ('development', 'NN'),
 ('potentially', 'RB'),
 ('politically', 'RB'),
 ('explosive', 'JJ'),
 ('investigation', 'NN'),
 ('neither', 'DT'),
 ('Chaffetz', 'NNP'),
 ('colleagues', 'NNS'),
 ('courtesy', 'VBP'),
 ('let', 'VB'),
 ('Democratic', 'JJ'),
 ('counterparts', 'NNS'),
 ('know', 'VBP'),
 ('Instead', 'RB'),
 ('according', 'VBG'),
 ('aide', 'RB'),
 ('made', 'VBN'),
 ('find', 'VBP'),
 ('Twitter', 'NNP'),
 ('already', 'RB'),
 ('talk', 'VB'),
 ('Daily', 'NNP'),
 ('Kos', 'NNP'),
 ('Comey', 'NNP'),
 ('provided', 'VBD'),
 ('advance', 'NN'),
 ('notice', 'NN'),
 ('letter', 'NN'),
 ('Chaffetz', 'NNP'),
 ('Republicans', 'NNPS'),
 ('giving', 'VBG'),
 ('time', 'NN'),
 ('turn', 'NN'),
 ('spin', 'JJ'),
 ('machine', 'NN'),
 ('may', 'MD'),
 ('make', 'VB'),
 ('good', 'JJ'),
 ('theater', 'NN'),
 ('nothing', 'NN'),
 ('far', 'RB'),
 ('even', 'RB'),
 ('suggests', 'VBZ'),
 ('case', 'NN'),
 ('nothing', 'NN'),
 ('far', 'RB'),
 ('suggests', 'VBZ'),
 ('Comey', 'NNP'),
 ('anything', 'NN'),
 ('grossly', 'RB'),
 ('incompetent', 'JJ'),
 ('suggest', 'VBP'),
 ('however', 'RB'),
 ('Chaffetz', 'NNP'),
 ('acting', 'VBG'),
 ('way', 'NN'),
 ('makes', 'VBZ'),
 ('Dan', 'NNP'),
 ('Burton', 'NNP'),
 ('Darrell', 'NNP'),
 ('Issa', 'NNP'),
 ('look', 'VBP'),
 ('like', 'IN'),
 ('models', 'NNS'),
 ('responsibility', 'VBP'),
 ('bipartisanship', 'RB'),
 ('even', 'RB'),
 ('decency', 'NN'),
 ('notify', 'JJ'),
 ('ranking', 'JJ'),
 ('member', 'NN'),
 ('Elijah', 'NNP'),
 ('Cummings', 'NNP'),
 ('something', 'NN'),
 ('explosive', 'JJ'),
 ('trample', 'NN'),
 ('basic', 'JJ'),
 ('standards', 'NNS'),
 ('fairness', 'NN'),
 ('know', 'VBP'),
 ('Granted', 'VBN'),
 ('likely', 'JJ'),
 ('Chaffetz', 'NNP'),
 ('answer', 'NN'),
 ('sits', 'VBZ'),
 ('ridiculously', 'RB'),
 ('Republican', 'JJ'),
 ('district', 'NN'),
 ('anchored', 'VBD'),
 ('Provo', 'NNP'),
 ('Orem', 'NNP'),
 ('Cook', 'NNP'),
 ('Partisan', 'NNP'),
 ('Voting', 'NNP'),
 ('Index', 'NNP'),
 ('gave', 'VBD'),
 ('Mitt', 'NNP'),
 ('Romney', 'NNP'),
 ('punishing', 'VBG'),
 ('78', 'CD'),
 ('percent', 'NN'),
 ('vote', 'NN'),
 ('2012', 'CD'),
 ('Moreover', 'RB'),
 ('Republican', 'NNP'),
 ('House', 'NNP'),
 ('leadership', 'NN'),
 ('given', 'VBN'),
 ('full', 'JJ'),
 ('support', 'NN'),
 ('Chaffetz', 'NNP'),
 ('planned', 'VBD'),
 ('fishing', 'VBG'),
 ('expedition', 'NN'),
 ('mean', 'JJ'),
 ('turn', 'NN'),
 ('hot', 'JJ'),
 ('lights', 'NNS'),
 ('textbook', 'VBP'),
 ('example', 'NN'),
 ('House', 'NNP'),
 ('become', 'VBZ'),
 ('Republican', 'NNP'),
 ('control', 'NN'),
 ('also', 'RB'),
 ('Second', 'NNP'),
 ('Worst', 'NNP'),
 ('Person', 'NNP'),
 ('World', 'NNP'),
 ('Darrell', 'NNP'),
 ('Lucus', 'NNP'),
 ('Darrell', 'NNP'),
 ('graduate', 'NN'),
 ('University', 'NNP'),
 ('North', 'NNP'),
 ('Carolina', 'NNP'),
 ('considers', 'NNS'),
 ('journalist', 'VBP'),
 ('old', 'JJ'),
 ('school', 'NN'),
 ('attempt', 'NN'),
 ('turn', 'VBP'),
 ('member', 'NN'),
 ('religious', 'JJ'),
 ('right', 'JJ'),
 ('college', 'NN'),
 ('succeeded', 'VBD'),
 ('turning', 'VBG'),
 ('religious', 'JJ'),
 ('right', 'JJ'),
 ('worst', 'JJS'),
 ('nightmare', 'JJ'),
 ('charismatic', 'JJ'),
 ('Christian', 'NNP'),
 ('unapologetic', 'JJ'),
 ('liberal', 'JJ'),
 ('desire', 'NN'),
 ('stand', 'NN'),
 ('scared', 'VBD'),
 ('silence', 'NN'),
 ('increased', 'VBD'),
 ('survived', 'VBN'),
 ('abusive', 'JJ'),
 ('marriage', 'NN'),
 ('may', 'MD'),
 ('know', 'VB'),
 ('Daily', 'NNP'),
 ('Kos', 'NNP'),
 ('Christian', 'NNP'),
 ('Dem', 'NNP'),
 ('NC', 'NNP'),
 ('Follow', 'NNP'),
 ('Twitter', 'NNP'),
 ('DarrellLucus', 'NNP'),
 ('connect', 'VBP'),
 ('Facebook', 'NNP'),
 ('Click', 'NNP'),
 ('buy', 'VB'),
 ('Darrell', 'NNP'),
 ('Mello', 'NNP'),
 ('Yello', 'NNP'),
 ('Connect', 'NNP')]

In [78]:
stemmed = []
stemmer = SnowballStemmer('english')
for word in clean:
    stemmed.append(stemmer.stem(word))

stemmed

['hous',
 'dem',
 'aid',
 'even',
 'see',
 'comey',
 'letter',
 'jason',
 'chaffetz',
 'tweet',
 'darrel',
 'lucus',
 'octob',
 '30',
 '2016',
 'subscrib',
 'jason',
 'chaffetz',
 'stump',
 'american',
 'fork',
 'utah',
 'imag',
 'courtesi',
 'michael',
 'jolley',
 'avail',
 'creativ',
 'licens',
 'apolog',
 'keith',
 'olbermann',
 'doubt',
 'worst',
 'person',
 'world',
 'director',
 'jame',
 'comey',
 'accord',
 'hous',
 'democrat',
 'aid',
 'look',
 'like',
 'also',
 'know',
 'person',
 'well',
 'turn',
 'comey',
 'sent',
 'letter',
 'announc',
 'fbi',
 'look',
 'email',
 'may',
 'relat',
 'hillari',
 'clinton',
 'email',
 'server',
 'rank',
 'democrat',
 'relev',
 'committe',
 'hear',
 'comey',
 'found',
 'via',
 'tweet',
 'one',
 'republican',
 'committe',
 'chairmen',
 'know',
 'comey',
 'notifi',
 'republican',
 'chairmen',
 'democrat',
 'rank',
 'member',
 'hous',
 'intellig',
 'judiciari',
 'oversight',
 'committe',
 'agenc',
 'review',
 'email',
 'recent',
 'discov',
 'order',
 'see',
 'contain',
 'classifi',
 'inform',
 'long',
 'letter',
 'went',
 'oversight',
 'committe',
 'chairman',
 'jason',
 'chaffetz',
 'set',
 'polit',
 'world',
 'ablaz',
 'tweet',
 'fbi',
 'dir',
 'inform',
 'fbi',
 'learn',
 'exist',
 'email',
 'appear',
 'pertin',
 'investig',
 'case',
 'reopen',
 'jason',
 'chaffetz',
 'jasoninthehous',
 'octob',
 '28',
 '2016',
 'cours',
 'know',
 'case',
 'comey',
 'actual',
 'say',
 'review',
 'email',
 'light',
 'unrel',
 'case',
 'know',
 'anthoni',
 'weiner',
 'sext',
 'teenag',
 'appar',
 'littl',
 'thing',
 'fact',
 'matter',
 'chaffetz',
 'utah',
 'republican',
 'alreadi',
 'vow',
 'initi',
 'raft',
 'investig',
 'hillari',
 'least',
 'two',
 'year',
 'worth',
 'possibl',
 'entir',
 'term',
 'worth',
 'appar',
 'chaffetz',
 'thought',
 'fbi',
 'alreadi',
 'work',
 'tweet',
 'briefli',
 'roil',
 'nation',
 'cooler',
 'head',
 'realiz',
 'dud',
 'accord',
 'senior',
 'hous',
 'democrat',
 'aid',
 'misread',
 'letter',
 'may',
 'least',
 'chaffetz',
 'sin',
 'aid',
 'told',
 'shareblu',
 'boss',
 'democrat',
 'even',
 'know',
 'comey',
 'letter',
 'found',
 'check',
 'twitter',
 'democrat',
 'rank',
 'member',
 'relev',
 'committe',
 'receiv',
 'comey',
 'letter',
 'republican',
 'chairmen',
 'fact',
 'democrat',
 'rank',
 'member',
 'receiv',
 'chairman',
 'oversight',
 'govern',
 'reform',
 'committe',
 'jason',
 'chaffetz',
 'tweet',
 'made',
 'let',
 'see',
 'got',
 'right',
 'fbi',
 'director',
 'tell',
 'chaffetz',
 'gop',
 'committe',
 'chairmen',
 'major',
 'develop',
 'potenti',
 'polit',
 'explos',
 'investig',
 'neither',
 'chaffetz',
 'colleagu',
 'courtesi',
 'let',
 'democrat',
 'counterpart',
 'know',
 'instead',
 'accord',
 'aid',
 'made',
 'find',
 'twitter',
 'alreadi',
 'talk',
 'daili',
 'kos',
 'comey',
 'provid',
 'advanc',
 'notic',
 'letter',
 'chaffetz',
 'republican',
 'give',
 'time',
 'turn',
 'spin',
 'machin',
 'may',
 'make',
 'good',
 'theater',
 'noth',
 'far',
 'even',
 'suggest',
 'case',
 'noth',
 'far',
 'suggest',
 'comey',
 'anyth',
 'grossli',
 'incompet',
 'suggest',
 'howev',
 'chaffetz',
 'act',
 'way',
 'make',
 'dan',
 'burton',
 'darrel',
 'issa',
 'look',
 'like',
 'model',
 'respons',
 'bipartisanship',
 'even',
 'decenc',
 'notifi',
 'rank',
 'member',
 'elijah',
 'cum',
 'someth',
 'explos',
 'trampl',
 'basic',
 'standard',
 'fair',
 'know',
 'grant',
 'like',
 'chaffetz',
 'answer',
 'sit',
 'ridicul',
 'republican',
 'district',
 'anchor',
 'provo',
 'orem',
 'cook',
 'partisan',
 'vote',
 'index',
 'gave',
 'mitt',
 'romney',
 'punish',
 '78',
 'percent',
 'vote',
 '2012',
 'moreov',
 'republican',
 'hous',
 'leadership',
 'given',
 'full',
 'support',
 'chaffetz',
 'plan',
 'fish',
 'expedit',
 'mean',
 'turn',
 'hot',
 'light',
 'textbook',
 'exampl',
 'hous',
 'becom',
 'republican',
 'control',
 'also',
 'second',
 'worst',
 'person',
 'world',
 'darrel',
 'lucus',
 'darrel',
 'graduat',
 'univers',
 'north',
 'carolina',
 'consid',
 'journalist',
 'old',
 'school',
 'attempt',
 'turn',
 'member',
 'religi',
 'right',
 'colleg',
 'succeed',
 'turn',
 'religi',
 'right',
 'worst',
 'nightmar',
 'charismat',
 'christian',
 'unapologet',
 'liber',
 'desir',
 'stand',
 'scare',
 'silenc',
 'increas',
 'surviv',
 'abus',
 'marriag',
 'may',
 'know',
 'daili',
 'kos',
 'christian',
 'dem',
 'nc',
 'follow',
 'twitter',
 'darrelllucus',
 'connect',
 'facebook',
 'click',
 'buy',
 'darrel',
 'mello',
 'yello',
 'connect']

In [82]:
lm = WordNetLemmatizer()
lemmatized = []
for word in clean:
    lemmatized.append(lm.lemmatize(word))
    
lemmatized

['House',
 'Dem',
 'Aide',
 'Even',
 'See',
 'Comey',
 'Letter',
 'Jason',
 'Chaffetz',
 'Tweeted',
 'Darrell',
 'Lucus',
 'October',
 '30',
 '2016',
 'Subscribe',
 'Jason',
 'Chaffetz',
 'stump',
 'American',
 'Fork',
 'Utah',
 'image',
 'courtesy',
 'Michael',
 'Jolley',
 'available',
 'Creative',
 'license',
 'apology',
 'Keith',
 'Olbermann',
 'doubt',
 'Worst',
 'Person',
 'World',
 'Director',
 'James',
 'Comey',
 'according',
 'House',
 'Democratic',
 'aide',
 'look',
 'like',
 'also',
 'know',
 'person',
 'well',
 'turn',
 'Comey',
 'sent',
 'letter',
 'announcing',
 'FBI',
 'looking',
 'email',
 'may',
 'related',
 'Hillary',
 'Clinton',
 'email',
 'server',
 'ranking',
 'Democrats',
 'relevant',
 'committee',
 'hear',
 'Comey',
 'found',
 'via',
 'tweet',
 'one',
 'Republican',
 'committee',
 'chairman',
 'know',
 'Comey',
 'notified',
 'Republican',
 'chairman',
 'Democratic',
 'ranking',
 'member',
 'House',
 'Intelligence',
 'Judiciary',
 'Oversight',
 'committee',
 'agency',
 'reviewing',
 'email',
 'recently',
 'discovered',
 'order',
 'see',
 'contained',
 'classified',
 'information',
 'long',
 'letter',
 'went',
 'Oversight',
 'Committee',
 'Chairman',
 'Jason',
 'Chaffetz',
 'set',
 'political',
 'world',
 'ablaze',
 'tweet',
 'FBI',
 'Dir',
 'informed',
 'FBI',
 'learned',
 'existence',
 'email',
 'appear',
 'pertinent',
 'investigation',
 'Case',
 'reopened',
 'Jason',
 'Chaffetz',
 'jasoninthehouse',
 'October',
 '28',
 '2016',
 'course',
 'know',
 'case',
 'Comey',
 'actually',
 'saying',
 'reviewing',
 'email',
 'light',
 'unrelated',
 'case',
 'know',
 'Anthony',
 'Weiner',
 'sexting',
 'teenager',
 'apparently',
 'little',
 'thing',
 'fact',
 'matter',
 'Chaffetz',
 'Utah',
 'Republican',
 'already',
 'vowed',
 'initiate',
 'raft',
 'investigation',
 'Hillary',
 'least',
 'two',
 'year',
 'worth',
 'possibly',
 'entire',
 'term',
 'worth',
 'Apparently',
 'Chaffetz',
 'thought',
 'FBI',
 'already',
 'work',
 'tweet',
 'briefly',
 'roiled',
 'nation',
 'cooler',
 'head',
 'realized',
 'dud',
 'according',
 'senior',
 'House',
 'Democratic',
 'aide',
 'misreading',
 'letter',
 'may',
 'least',
 'Chaffetz',
 'sin',
 'aide',
 'told',
 'Shareblue',
 'bos',
 'Democrats',
 'even',
 'know',
 'Comey',
 'letter',
 'found',
 'checked',
 'Twitter',
 'Democratic',
 'Ranking',
 'Members',
 'relevant',
 'committee',
 'receive',
 'Comey',
 'letter',
 'Republican',
 'Chairmen',
 'fact',
 'Democratic',
 'Ranking',
 'Members',
 'receive',
 'Chairman',
 'Oversight',
 'Government',
 'Reform',
 'Committee',
 'Jason',
 'Chaffetz',
 'tweeted',
 'made',
 'let',
 'see',
 'got',
 'right',
 'FBI',
 'director',
 'tell',
 'Chaffetz',
 'GOP',
 'committee',
 'chairman',
 'major',
 'development',
 'potentially',
 'politically',
 'explosive',
 'investigation',
 'neither',
 'Chaffetz',
 'colleague',
 'courtesy',
 'let',
 'Democratic',
 'counterpart',
 'know',
 'Instead',
 'according',
 'aide',
 'made',
 'find',
 'Twitter',
 'already',
 'talk',
 'Daily',
 'Kos',
 'Comey',
 'provided',
 'advance',
 'notice',
 'letter',
 'Chaffetz',
 'Republicans',
 'giving',
 'time',
 'turn',
 'spin',
 'machine',
 'may',
 'make',
 'good',
 'theater',
 'nothing',
 'far',
 'even',
 'suggests',
 'case',
 'nothing',
 'far',
 'suggests',
 'Comey',
 'anything',
 'grossly',
 'incompetent',
 'suggest',
 'however',
 'Chaffetz',
 'acting',
 'way',
 'make',
 'Dan',
 'Burton',
 'Darrell',
 'Issa',
 'look',
 'like',
 'model',
 'responsibility',
 'bipartisanship',
 'even',
 'decency',
 'notify',
 'ranking',
 'member',
 'Elijah',
 'Cummings',
 'something',
 'explosive',
 'trample',
 'basic',
 'standard',
 'fairness',
 'know',
 'Granted',
 'likely',
 'Chaffetz',
 'answer',
 'sits',
 'ridiculously',
 'Republican',
 'district',
 'anchored',
 'Provo',
 'Orem',
 'Cook',
 'Partisan',
 'Voting',
 'Index',
 'gave',
 'Mitt',
 'Romney',
 'punishing',
 '78',
 'percent',
 'vote',
 '2012',
 'Moreover',
 'Republican',
 'House',
 'leadership',
 'given',
 'full',
 'support',
 'Chaffetz',
 'planned',
 'fishing',
 'expedition',
 'mean',
 'turn',
 'hot',
 'light',
 'textbook',
 'example',
 'House',
 'become',
 'Republican',
 'control',
 'also',
 'Second',
 'Worst',
 'Person',
 'World',
 'Darrell',
 'Lucus',
 'Darrell',
 'graduate',
 'University',
 'North',
 'Carolina',
 'considers',
 'journalist',
 'old',
 'school',
 'attempt',
 'turn',
 'member',
 'religious',
 'right',
 'college',
 'succeeded',
 'turning',
 'religious',
 'right',
 'worst',
 'nightmare',
 'charismatic',
 'Christian',
 'unapologetic',
 'liberal',
 'desire',
 'stand',
 'scared',
 'silence',
 'increased',
 'survived',
 'abusive',
 'marriage',
 'may',
 'know',
 'Daily',
 'Kos',
 'Christian',
 'Dem',
 'NC',
 'Follow',
 'Twitter',
 'DarrellLucus',
 'connect',
 'Facebook',
 'Click',
 'buy',
 'Darrell',
 'Mello',
 'Yello',
 'Connect']

In [86]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform([' '.join(lemmatized)])
tfidf_matrix.shape

(1, 267)

In [88]:
corpus = df['text']

vectorizer = TfidfVectorizer(max_features=5000)

In [92]:
tf = Counter(clean)

total_words = len(clean)

tf_normal = {word: count/total_words for word,count in tf.items()}

print(tf_normal)

{'House': 0.014184397163120567, 'Dem': 0.004728132387706856, 'Aide': 0.002364066193853428, 'Even': 0.002364066193853428, 'See': 0.002364066193853428, 'Comey': 0.02364066193853428, 'Letter': 0.002364066193853428, 'Jason': 0.01182033096926714, 'Chaffetz': 0.03309692671394799, 'Tweeted': 0.002364066193853428, 'Darrell': 0.01182033096926714, 'Lucus': 0.004728132387706856, 'October': 0.004728132387706856, '30': 0.002364066193853428, '2016': 0.004728132387706856, 'Subscribe': 0.002364066193853428, 'stump': 0.002364066193853428, 'American': 0.002364066193853428, 'Fork': 0.002364066193853428, 'Utah': 0.004728132387706856, 'image': 0.002364066193853428, 'courtesy': 0.004728132387706856, 'Michael': 0.002364066193853428, 'Jolley': 0.002364066193853428, 'available': 0.002364066193853428, 'Creative': 0.002364066193853428, 'license': 0.002364066193853428, 'apologies': 0.002364066193853428, 'Keith': 0.002364066193853428, 'Olbermann': 0.002364066193853428, 'doubt': 0.002364066193853428, 'Worst': 0.004728132387706856, 'Person': 0.004728132387706856, 'World': 0.004728132387706856, 'Director': 0.002364066193853428, 'James': 0.002364066193853428, 'according': 0.0070921985815602835, 'Democratic': 0.014184397163120567, 'aide': 0.009456264775413711, 'looks': 0.002364066193853428, 'like': 0.004728132387706856, 'also': 0.004728132387706856, 'know': 0.018912529550827423, 'person': 0.002364066193853428, 'well': 0.002364066193853428, 'turns': 0.002364066193853428, 'sent': 0.002364066193853428, 'letter': 0.014184397163120567, 'announcing': 0.002364066193853428, 'FBI': 0.01182033096926714, 'looking': 0.002364066193853428, 'emails': 0.009456264775413711, 'may': 0.009456264775413711, 'related': 0.002364066193853428, 'Hillary': 0.004728132387706856, 'Clinton': 0.002364066193853428, 'email': 0.002364066193853428, 'server': 0.002364066193853428, 'ranking': 0.0070921985815602835, 'Democrats': 0.004728132387706856, 'relevant': 0.004728132387706856, 'committees': 0.0070921985815602835, 'hear': 0.002364066193853428, 'found': 0.004728132387706856, 'via': 0.002364066193853428, 'tweet': 0.0070921985815602835, 'one': 0.002364066193853428, 'Republican': 0.016548463356973995, 'committee': 0.004728132387706856, 'chairmen': 0.0070921985815602835, 'notified': 0.002364066193853428, 'members': 0.002364066193853428, 'Intelligence': 0.002364066193853428, 'Judiciary': 0.002364066193853428, 'Oversight': 0.0070921985815602835, 'agency': 0.002364066193853428, 'reviewing': 0.004728132387706856, 'recently': 0.002364066193853428, 'discovered': 0.002364066193853428, 'order': 0.002364066193853428, 'see': 0.004728132387706856, 'contained': 0.002364066193853428, 'classified': 0.002364066193853428, 'information': 0.002364066193853428, 'long': 0.002364066193853428, 'went': 0.002364066193853428, 'Committee': 0.004728132387706856, 'Chairman': 0.004728132387706856, 'set': 0.002364066193853428, 'political': 0.002364066193853428, 'world': 0.002364066193853428, 'ablaze': 0.002364066193853428, 'Dir': 0.002364066193853428, 'informed': 0.002364066193853428, 'learned': 0.002364066193853428, 'existence': 0.002364066193853428, 'appear': 0.002364066193853428, 'pertinent': 0.002364066193853428, 'investigation': 0.004728132387706856, 'Case': 0.002364066193853428, 'reopened': 0.002364066193853428, 'jasoninthehouse': 0.002364066193853428, '28': 0.002364066193853428, 'course': 0.002364066193853428, 'case': 0.0070921985815602835, 'actually': 0.002364066193853428, 'saying': 0.002364066193853428, 'light': 0.002364066193853428, 'unrelated': 0.002364066193853428, 'Anthony': 0.002364066193853428, 'Weiner': 0.002364066193853428, 'sexting': 0.002364066193853428, 'teenager': 0.002364066193853428, 'apparently': 0.002364066193853428, 'little': 0.002364066193853428, 'things': 0.002364066193853428, 'facts': 0.002364066193853428, 'matter': 0.002364066193853428, 'already': 0.0070921985815602835, 'vowed': 0.002364066193853428, 'initiate': 0.002364066193853428, 'raft': 0.002364066193853428, 'investigations': 0.002364066193853428, 'least': 0.004728132387706856, 'two': 0.002364066193853428, 'years': 0.002364066193853428, 'worth': 0.004728132387706856, 'possibly': 0.002364066193853428, 'entire': 0.002364066193853428, 'term': 0.002364066193853428, 'Apparently': 0.002364066193853428, 'thought': 0.002364066193853428, 'work': 0.002364066193853428, 'briefly': 0.002364066193853428, 'roiled': 0.002364066193853428, 'nation': 0.002364066193853428, 'cooler': 0.002364066193853428, 'heads': 0.002364066193853428, 'realized': 0.002364066193853428, 'dud': 0.002364066193853428, 'senior': 0.002364066193853428, 'misreading': 0.002364066193853428, 'sins': 0.002364066193853428, 'told': 0.002364066193853428, 'Shareblue': 0.002364066193853428, 'boss': 0.002364066193853428, 'even': 0.0070921985815602835, 'checked': 0.002364066193853428, 'Twitter': 0.0070921985815602835, 'Ranking': 0.004728132387706856, 'Members': 0.004728132387706856, 'receive': 0.004728132387706856, 'Chairmen': 0.002364066193853428, 'fact': 0.002364066193853428, 'Government': 0.002364066193853428, 'Reform': 0.002364066193853428, 'tweeted': 0.002364066193853428, 'made': 0.004728132387706856, 'let': 0.004728132387706856, 'got': 0.002364066193853428, 'right': 0.0070921985815602835, 'director': 0.002364066193853428, 'tells': 0.002364066193853428, 'GOP': 0.002364066193853428, 'major': 0.002364066193853428, 'development': 0.002364066193853428, 'potentially': 0.002364066193853428, 'politically': 0.002364066193853428, 'explosive': 0.004728132387706856, 'neither': 0.002364066193853428, 'colleagues': 0.002364066193853428, 'counterparts': 0.002364066193853428, 'Instead': 0.002364066193853428, 'find': 0.002364066193853428, 'talk': 0.002364066193853428, 'Daily': 0.004728132387706856, 'Kos': 0.004728132387706856, 'provided': 0.002364066193853428, 'advance': 0.002364066193853428, 'notice': 0.002364066193853428, 'Republicans': 0.002364066193853428, 'giving': 0.002364066193853428, 'time': 0.002364066193853428, 'turn': 0.0070921985815602835, 'spin': 0.002364066193853428, 'machine': 0.002364066193853428, 'make': 0.002364066193853428, 'good': 0.002364066193853428, 'theater': 0.002364066193853428, 'nothing': 0.004728132387706856, 'far': 0.004728132387706856, 'suggests': 0.004728132387706856, 'anything': 0.002364066193853428, 'grossly': 0.002364066193853428, 'incompetent': 0.002364066193853428, 'suggest': 0.002364066193853428, 'however': 0.002364066193853428, 'acting': 0.002364066193853428, 'way': 0.002364066193853428, 'makes': 0.002364066193853428, 'Dan': 0.002364066193853428, 'Burton': 0.002364066193853428, 'Issa': 0.002364066193853428, 'look': 0.002364066193853428, 'models': 0.002364066193853428, 'responsibility': 0.002364066193853428, 'bipartisanship': 0.002364066193853428, 'decency': 0.002364066193853428, 'notify': 0.002364066193853428, 'member': 0.004728132387706856, 'Elijah': 0.002364066193853428, 'Cummings': 0.002364066193853428, 'something': 0.002364066193853428, 'trample': 0.002364066193853428, 'basic': 0.002364066193853428, 'standards': 0.002364066193853428, 'fairness': 0.002364066193853428, 'Granted': 0.002364066193853428, 'likely': 0.002364066193853428, 'answer': 0.002364066193853428, 'sits': 0.002364066193853428, 'ridiculously': 0.002364066193853428, 'district': 0.002364066193853428, 'anchored': 0.002364066193853428, 'Provo': 0.002364066193853428, 'Orem': 0.002364066193853428, 'Cook': 0.002364066193853428, 'Partisan': 0.002364066193853428, 'Voting': 0.002364066193853428, 'Index': 0.002364066193853428, 'gave': 0.002364066193853428, 'Mitt': 0.002364066193853428, 'Romney': 0.002364066193853428, 'punishing': 0.002364066193853428, '78': 0.002364066193853428, 'percent': 0.002364066193853428, 'vote': 0.002364066193853428, '2012': 0.002364066193853428, 'Moreover': 0.002364066193853428, 'leadership': 0.002364066193853428, 'given': 0.002364066193853428, 'full': 0.002364066193853428, 'support': 0.002364066193853428, 'planned': 0.002364066193853428, 'fishing': 0.002364066193853428, 'expedition': 0.002364066193853428, 'mean': 0.002364066193853428, 'hot': 0.002364066193853428, 'lights': 0.002364066193853428, 'textbook': 0.002364066193853428, 'example': 0.002364066193853428, 'become': 0.002364066193853428, 'control': 0.002364066193853428, 'Second': 0.002364066193853428, 'graduate': 0.002364066193853428, 'University': 0.002364066193853428, 'North': 0.002364066193853428, 'Carolina': 0.002364066193853428, 'considers': 0.002364066193853428, 'journalist': 0.002364066193853428, 'old': 0.002364066193853428, 'school': 0.002364066193853428, 'attempt': 0.002364066193853428, 'religious': 0.004728132387706856, 'college': 0.002364066193853428, 'succeeded': 0.002364066193853428, 'turning': 0.002364066193853428, 'worst': 0.002364066193853428, 'nightmare': 0.002364066193853428, 'charismatic': 0.002364066193853428, 'Christian': 0.004728132387706856, 'unapologetic': 0.002364066193853428, 'liberal': 0.002364066193853428, 'desire': 0.002364066193853428, 'stand': 0.002364066193853428, 'scared': 0.002364066193853428, 'silence': 0.002364066193853428, 'increased': 0.002364066193853428, 'survived': 0.002364066193853428, 'abusive': 0.002364066193853428, 'marriage': 0.002364066193853428, 'NC': 0.002364066193853428, 'Follow': 0.002364066193853428, 'DarrellLucus': 0.002364066193853428, 'connect': 0.002364066193853428, 'Facebook': 0.002364066193853428, 'Click': 0.002364066193853428, 'buy': 0.002364066193853428, 'Mello': 0.002364066193853428, 'Yello': 0.002364066193853428, 'Connect': 0.002364066193853428}

In [94]:
documents = corpus.tolist()
N = len(documents)

word_doc_count = {}

for doc in documents:
    words = set(doc.split())
    for word in words:
        word_doc_count[word] = word_doc_count.get(word,0)+1

idf = {word: math.log(N/count) for word,count in word_doc_count.items()}

print('IDF:\n', dict(list(idf.items())[:20]))

IDF:
 {'Follow': 2.21649561518188, 'Dem': 6.279146619559763, 'a': 0.0813456394539524, 'Aide:': 9.94270826568941, 'Worst': 6.3591893272333, 'one': 0.5989740105426956, 'license)': 8.333270353255308, 'and': 0.08296363610120012, 'scared': 4.600374013724599, 'but': 0.5056308068888866, 'Jason': 4.007814070069822, 'we': 0.7661315238660358, 'into': 0.752978847617351, 'I': 0.8273381313044534, 'is': 0.1544632286655582, 'until': 1.82718738414264, 'so': 0.8683021709540597, 'Comey’s': 4.259128498350727, 'percent': 1.9692083016647794, 'With': 2.0498827394382917}

In [98]:
tfidf_matrix = vectorizer.fit_transform(documents)
tfidf_matrix.shape

(20800, 5000)

In [100]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns = vectorizer.get_feature_names_out()
)

In [101]:
tfidf_df

,00,000,10,100,11,12,125,13,14,15,...,как,мы,на,не,но,по,сша,то,что,это
0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.000000,0.000000,0.0,0.016310,0.000000,0.0,0.020081,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.029306,0.000000,0.099468,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20795,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20796,0.0,0.000000,0.000000,0.0,0.015128,0.000000,0.0,0.000000,0.018691,0.015805,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20797,0.0,0.017190,0.017855,0.0,0.041468,0.022973,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20798,0.0,0.000000,0.036846,0.0,0.042787,0.000000,0.0,0.052681,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20799,0.0,0.041251,0.000000,0.0,0.016585,0.000000,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0